In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv("CKD.csv")

In [3]:
df.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.0,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.0,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.0,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.0,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.0,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes


In [4]:
dup_count=df.duplicated().sum()
print('Printing Duplicate Count', df.duplicated().sum())

Printing Duplicate Count 0


In [5]:
print("Missing Value Check")
df.isnull().sum()

Missing Value Check


age               0
bp                0
sg                0
al                0
su                0
rbc               0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sc                0
sod               0
pot               0
hrmo              0
pcv               0
wc                0
rc                0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
classification    0
dtype: int64

In [6]:
print("Shape of the Dateset :",df.shape)
print("Rows :", df.shape[0])
print("Columns :",df.shape[1])
print("\nDataset Columns and Types:")
print(df.dtypes)

Shape of the Dateset : (399, 25)
Rows : 399
Columns : 25

Dataset Columns and Types:
age               float64
bp                float64
sg                 object
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hrmo              float64
pcv               float64
wc                float64
rc                float64
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object


In [7]:
df['appet'] = df['appet'].map({'poor': 0, 'yes': 1})
df['classification'] = df['classification'].map({'no': 0, 'yes': 1})

In [8]:
df.nunique()

age                77
bp                 11
sg                  5
al                  6
su                  6
rbc                 2
pc                  2
pcc                 2
ba                  2
bgr               147
bu                119
sc                 85
sod                35
pot                41
hrmo              116
pcv                43
wc                 90
rc                 46
htn                 2
dm                  2
cad                 2
appet               2
pe                  2
ane                 2
classification      2
dtype: int64

In [9]:
for col in df.columns:
    unique_vals = df[col].unique()
    print("-"*60)
    print(f"Column: {col}")
    print(f"Total Unique Count: {len(unique_vals)}")
    print(f"Values: {unique_vals}")
    print("-" * 30)

------------------------------------------------------------
Column: age
Total Unique Count: 77
Values: [ 2.          3.          4.          5.          6.          7.
  8.         11.         12.         14.         15.         17.
 19.         20.         21.         22.         23.         24.
 25.         26.         27.         28.         29.         30.
 32.         33.         34.         35.         36.         37.
 38.         39.         40.         41.         42.         43.
 44.         45.         46.         47.         48.         49.
 50.         51.         52.         53.         54.         55.
 56.         57.         58.         59.         60.         61.
 62.         63.         64.         65.         66.         67.
 68.         69.         70.         71.         72.         73.
 74.         75.         76.         78.         79.         80.
 81.         82.         83.         90.         51.49230769]
------------------------------
-----------------------

In [10]:
print(df.dtypes)

age               float64
bp                float64
sg                 object
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hrmo              float64
pcv               float64
wc                float64
rc                float64
htn                object
dm                 object
cad                object
appet               int64
pe                 object
ane                object
classification      int64
dtype: object


In [11]:
mapping = {
    'normal': 1, 'abnormal': 0,
    'present': 1, 'notpresent': 0,
    'yes': 1, 'no': 0,
    'poor': 0 
}

binary_cols = ['rbc', 'pc', 'pcc', 'ba', 'htn', 'dm', 'cad', 'pe', 'ane']

for col in binary_cols:
    df[col] = df[col].map(mapping)

df_final = pd.get_dummies(df, drop_first=True)

In [12]:
df_final.head(5)

,age,bp,al,su,rbc,pc,pcc,ba,bgr,bu,sc,sod,pot,hrmo,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification,sg_b,sg_c,sg_d,sg_e
0,2.0,76.459948,3.0,0.0,1,0,0,0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,38.868902,8408.191126,4.705597,0,0,0,1,1,0,1,False,True,False,False
1,3.0,76.459948,2.0,0.0,1,1,0,0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,34.000000,12300.000000,4.705597,0,0,0,1,0,0,1,False,True,False,False
2,4.0,76.459948,1.0,0.0,1,1,0,0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,34.000000,8408.191126,4.705597,0,0,0,1,0,0,1,False,False,False,False
3,5.0,76.459948,1.0,0.0,1,1,0,0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,38.868902,8408.191126,4.705597,0,0,0,1,0,1,1,False,False,True,False
4,5.0,50.000000,0.0,0.0,1,1,0,0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,36.000000,12400.000000,4.705597,0,0,0,1,0,0,1,False,True,False,False


In [13]:
df_final = df_final.astype(int)

In [14]:
for col in df_final.columns:
    unique_vals = df_final[col].unique()
    print("-"*60)
    print(f"Column: {col}")
    print(f"Total Unique Count: {len(unique_vals)}")
    print(f"Values: {unique_vals}")
    print("-" * 30)

------------------------------------------------------------
Column: age
Total Unique Count: 76
Values: [ 2  3  4  5  6  7  8 11 12 14 15 17 19 20 21 22 23 24 25 26 27 28 29 30
 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55
 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 78 79 80
 81 82 83 90]
------------------------------
------------------------------------------------------------
Column: bp
Total Unique Count: 11
Values: [ 76  50  60  80  70  90 100 110 140 120 180]
------------------------------
------------------------------------------------------------
Column: al
Total Unique Count: 6
Values: [3 2 1 0 4 5]
------------------------------
------------------------------------------------------------
Column: su
Total Unique Count: 6
Values: [0 4 3 2 1 5]
------------------------------
------------------------------------------------------------
Column: rbc
Total Unique Count: 2
Values: [1 0]
------------------------------
------------------

In [15]:
X = df_final.drop(columns=['classification'])
y = df_final['classification']

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [17]:
classifier_log = LogisticRegression(random_state=0)
classifier_log.fit(X_train, y_train)

y_pred_log = classifier_log.predict(X_test)
print("Logistic Regression Confusion Matrix:\n", confusion_matrix(y_test, y_pred_log))
print("\nReport:\n", classification_report(y_test, y_pred_log))

Logistic Regression Confusion Matrix:
 [[51  0]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [18]:
classifier_svm = SVC(kernel='sigmoid', probability=True, random_state=0)
classifier_svm.fit(X_train, y_train)

y_pred_svm = classifier_svm.predict(X_test)
print("SVM Confusion Matrix:\n", confusion_matrix(y_test, y_pred_svm))
print("\nReport:\n", classification_report(y_test, y_pred_svm))

SVM Confusion Matrix:
 [[51  0]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      1.00      0.99        51
           1       1.00      0.99      0.99        82

    accuracy                           0.99       133
   macro avg       0.99      0.99      0.99       133
weighted avg       0.99      0.99      0.99       133



In [19]:
classifier_rf = RandomForestClassifier(n_estimators=100, criterion='entropy', random_state=0)
classifier_rf.fit(X_train, y_train)

y_pred_rf = classifier_rf.predict(X_test)
print("Random Forest Confusion Matrix:\n", confusion_matrix(y_test, y_pred_rf))
print("\nReport:\n", classification_report(y_test, y_pred_rf))

Random Forest Confusion Matrix:
 [[50  1]
 [ 1 81]]

Report:
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133



In [20]:
classifier_knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(X_train, y_train)

y_pred_knn = classifier_knn.predict(X_test)
print("KNN Confusion Matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("\nReport:\n", classification_report(y_test, y_pred_knn))

KNN Confusion Matrix:
 [[51  0]
 [ 6 76]]

Report:
               precision    recall  f1-score   support

           0       0.89      1.00      0.94        51
           1       1.00      0.93      0.96        82

    accuracy                           0.95       133
   macro avg       0.95      0.96      0.95       133
weighted avg       0.96      0.95      0.96       133



In [21]:
classifier_nb = GaussianNB()
classifier_nb.fit(X_train, y_train)

y_pred_nb = classifier_nb.predict(X_test)
print("Naive Bayes Confusion Matrix:\n", confusion_matrix(y_test, y_pred_nb))
print("\nReport:\n", classification_report(y_test, y_pred_nb))

Naive Bayes Confusion Matrix:
 [[51  0]
 [ 3 79]]

Report:
               precision    recall  f1-score   support

           0       0.94      1.00      0.97        51
           1       1.00      0.96      0.98        82

    accuracy                           0.98       133
   macro avg       0.97      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133



In [22]:
scores = cross_val_score(classifier_rf, X, y, cv=5)

print("Cross-Validation Accuracy Scores:", scores)
print("Average Accuracy: {:.2f}%".format(scores.mean() * 100))

Cross-Validation Accuracy Scores: [0.9375 1.     0.975  0.9875 1.    ]
Average Accuracy: 98.00%
